name: "Tuzuru - Generate Blog"
description: "Install tuzuru via npm and run 'tuzuru generate'"

inputs:
  config:
    description: "Path to tuzuru.json (relative to working-directory)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '22'

    - name: Install Tuzuru
      shell: bash
      run: npm install -g @ainame/tuzuru@0.4.0 # x-release-please-version

    - name: Generate blog
      shell: bash
      run: |
        set -euo pipefail
        if [[ -n "${{ inputs.config }}" ]]; then
          tuzuru generate -c "${{ inputs.config }}"
        else
          tuzuru generate
        fi
