included:
  - Sources
  - Tests

disabled_rules:
  - line_length
  - file_length
  - function_body_length
  - type_body_length
  - large_tuple
  - unused_closure_parameter
  - optional_data_string_conversion

trailing_comma:
  mandatory_comma: true
